version: 2.0.0.{build}

platform:
  - Win32
  - x64

image:
 - Visual Studio 2015
 - Visual Studio 2017

configuration:
  - Release
  - Debug

environment:
  global:
    CTEST_OUTPUT_ON_FAILURE: 1

  matrix:
    - BUILD_SHARED_LIBS: ON
    - BUILD_SHARED_LIBS: OFF


clone_folder: c:\dev\robot-testing-framework

init:
  # System related variables
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR=Visual Studio 15 2017
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set CMAKE_GENERATOR=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - cmd: echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

build_script:
  - cd c:\dev\robot-testing-framework
  - md build
  - cd build
  - cmake -G"%CMAKE_GENERATOR%" -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% ..
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%platform%" RobotTestingFramework.sln

test_script:
  - cmd: ctest --output-on-failure --build-config %CONFIGURATION%
